### ISSUE TITLE
404 after signing in

### ISSUE THREAD

**Issue by vm206** [calculist/calculist#5]
I just registered with the invite code I received, and clicked on sign up or similar button, then got a plain white page (url: https://app.calculist.io/<username>) with text: 404.
I also tried from a different browser not having any possible session history for Calculist, but same result after login.

**Comment by danallison** [comment]
Shoot. I thought I fixed that. Try navigating directly to app.calculist.io/username (where "username" is your username) after signing in. Thanks for reporting this.

**Comment by danallison** [comment]
Ok. I just deployed an update that should fix the issue. Can you confirm that it has been fixed?

**Comment by danallison** [comment]
Closing this, as it appears to be fixed.

**Comment by vm206** [comment]
Hi Dan, still the same unfortunately. My username contains a dot, maybe that might be the issue?

**Comment by danallison** [comment]
Yes. That would do it. I have removed the dot from your username, so you should be able to access your account now. I will open a new issue to prevent usernames that can't be used in urls.

**Comment by vm206** [comment]
thanks, now works...
